name: RSpec Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0, 3.1, 3.2]
        rails-version: [5.2, 6.1, 7.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: default
          bundler-cache: true

      - name: Remove Bundler frozen setting
        run: bundle config set --local frozen 'false'

      - name: Install dependencies
        run: |
          echo "gem 'rails', '~> ${{ matrix.rails-version }}'" >> Gemfile
          bundle install

      - name: Run RSpec
        run: bundle exec rspec